export const API_PATH = {
  LOGIN: '/login',
  STUDENT: '/student',
  STAFF: '/staff',
  STAFF_SALARY: '/salary',
  PROMOTE_STAFF: '/promote-user',
  REVOKE_STAFF_PROMOTION: '/delete-user',
  STAFF_ATTENDANCE: '/staff-attendance',
  STAFF_ATTENDANCE_SUMMARY: '/staff-attendance/summary',
  STUDENT_ATTENDANCE: '/student-attendance',
  STUDENT_ATTENDANCE_SUMMARY: '/student-attendance/summary',
  ATTENDANCE_SUMMARY: '/attendance/summary',
  STUDENT_ATTENDANCE_DAY: '/attendance/student',
  STAFF_ATTENDANCE_DAY: '/attendance/staff',
  STUDENT_FEES: '/fees',
};
